In [1]:
import requests
import pandas as pd

In [2]:
licence='30294013744efca1c'

In [3]:
def mydata_get(url:str)->pd.DataFrame:
    response = requests.get(url)
    data = response.json()
    return pd.DataFrame(data)

## [沪深基础数据](http://api.mairui.club/hsdata.html)
### 股票列表

#### 沪深两市股票
- 字段
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |dm|string|股票的六位交易代码，例如：601398|
    |mc|string|股票名称，例如：工商银行|
    |jys|string|交易所，"sh"表示上证，"sz"表示深证|
- api接口：`http://api.mairui.club/hslt/list/您的licence`

In [4]:
url=f'http://api.mairui.club/hslt/list/{licence}'
df=mydata_get(url)

In [5]:
df.head()

       dm    mc jys
0  300198  纳川股份  sz
1  688073  毕得医药  sh
2  688535  华海诚科  sh
3  301141  中科磁业  sz
4  301186  超达装备  sz

In [6]:
df[df['dm']=='300198']

       dm    mc jys
0  300198  纳川股份  sz

#### 沪深两市新股日历
- 字段：
    | 字段名称 | 数据类型 | 字段说明 |
    | --- | --- | --- |
    |zqdm|string|股票代码|
    |zqjc|string|股票简称|
    |sgdm|string|申购代码|
    |fxsl|number|发行总数（股）|
    |swfxsl|number|网上发行（股）|
    |sgsx|number|申购上限（股）|
    |dgsz|number|顶格申购需配市值(元)|
    |sgrq|string|申购日期|
    |fxjg|number|发行价格（元），null为“未知”|
    |zxj|number|最新价（元），null为“未知”|
    |srspj|number|首日收盘价（元），null为“未知”|
    |zqgbrq|string|中签号公布日，null为未知|
    |zqjkrq|string|中签缴款日，null为未知|
    |ssrq|string|上市日期，null为未知|
    |syl|number|发行市盈率，null为“未知”|
    |hysyl|number|行业市盈率|
    |wszql|number|中签率（%），null为“未知”|
    |yzbsl|number|连续一字板数量，null为“未知”|
    |zf|number|涨幅（%），null为“未知”|
    |yqhl|number|每中一签获利（元），null为“未知”|
    |zyyw|string|主营业务|
- api接口：`http://api.mairui.club/hslt/new/您的licence`

In [7]:
url=f'http://api.mairui.club/hslt/new/{licence}'

In [8]:
df=mydata_get(url)

In [9]:
df.head()

,zqdm,zqjc,sgdm,fxsl,swfxsl,sgsx,dgsz,sgrq,fxjg,zxj,...,zqgbrq,zqjkrq,ssrq,syl,hysyl,wszql,yzbsl,zf,yqhl,zyyw
0,301371,敷尔佳,301371,40080000,7615000,7500,75000,2023-07-20,None,0,...,2023-07-24,2023-07-24,None,None,15.48,None,0,None,None,从事专业皮肤护理产品的研发、生产和销售
1,688646,逸飞激光,787646,23790652.0000,5709500,5500,55000,2023-07-19,None,0,...,2023-07-21,2023-07-21,None,None,30.76,None,0,None,None,从事精密激光加工智能装备研发、设计、生产和销售
2,603119,浙江荣泰,732119,70000000,28000000,28000,280000,2023-07-19,None,0,...,2023-07-21,2023-07-21,None,None,17.44,None,0,None,None,各类耐高温绝缘云母制品的研发、生产和销售
3,688651,盛邦安全,787651,18880000,4814000,4500,45000,2023-07-17,None,0,...,2023-07-19,2023-07-19,None,None,73.73,None,0,None,None,网络安全产品的研发、生产和销售
4,688612,威迈斯,787612,42100000,6736000,6500,65000,2023-07-17,None,0,...,2023-07-19,2023-07-19,None,None,26.52,None,0,None,None,从事新能源汽车相关电力电子产品的研发、生产、销售和技术服务

### 指数、行业、概念列表

#### 指数、行业、概念
- API接口：http://api.mairui.club/hszg/list/您的licence
- 备用接口：http://api1.mairui.club/hszg/list/您的licence
- 接口说明：获取指数、行业、概念（包括基金，债券，美股，外汇，期货，黄金等的代码），其中isleaf为1（叶子节点）的记录的code（代码）可以作为下方接口的参数传入，从而得到某个指数、行业、概念下的相关股票。
- 数据更新：每周六03:00更新
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |code|string|代码|
    |name|string|名称|
    |type1|number|一级分类（0:A股,1:创业板,2:科创板,3:基金,4:香港股市,5:债券,6:美国股市,7:外汇,8:期货,9:黄金,10:英国股市）|
    |type2|number|二级分类（0:A股-申万行业,1:A股-申万二级,2:A股-热门概念,3:A股-概念板块,4:A股-地域板块,5:A股-证监会行业,6:A股-分类,7:A股-指数成分,8:A股-风险警示,9:A股-大盘指数,10:A股-次新股,11:A股-沪港通,12:A股-深港通,13:基金-封闭式基金,14:基金-开放式基金,15:基金-货币型基金,16:基金-ETF基金净值,17:基金-ETF基金行情,18:基金-LOF基金行情,21:基金-科创板基金,22:香港股市-恒生行业,23:香港股市-全部港股,24:香港股市-热门港股,25:香港股市-蓝筹股,26:香港股市-红筹股,27:香港股市-国企股,28:香港股市-创业板,29:香港股市-指数,30:香港股市-A+H,31:香港股市-窝轮,32:香港股市-ADR,33:香港股市-沪港通,34:香港股市-深港通,35:香港股市-中华系列指数,36:债券-沪深债券,37:债券-深市债券,38:债券-沪市债券,39:债券-沪深可转债,40:美国股市-中国概念股,41:美国股市-科技类,42:美国股市-金融类,43:美国股市-制造零售类,44:美国股市-汽车能源类,45:美国股市-媒体类,46:美国股市-医药食品类,48:外汇-基本汇率,49:外汇-热门汇率,50:外汇-所有汇率,51:外汇-交叉盘汇率,52:外汇-美元相关汇率,53:外汇-人民币相关汇率,54:期货-全球期货,55:期货-中国金融期货交易所,56:期货-上海期货交易所,57:期货-大连商品交易所,58:期货-郑州商品交易所,59:黄金-黄金现货,60:黄金-黄金期货|
    |level|number|层级，从0开始，根节点为0，二级节点为1，以此类推|
    |pcode|string|父节点代码|
    |pname|string|父节点名称|
    |isleaf|number|是否为叶子节点，0：否，1：是|

In [10]:
url=f'http://api.mairui.club/hszg/list/{licence}'
df=mydata_get(url)

In [11]:
df.head()

      code          name type1 type2 level pcode    pname isleaf
0    sw_mt    A股-申万行业-煤炭     0     0     2  swhy  A股-申万行业      1
1  sw_sysh  A股-申万行业-石油石化     0     0     2  swhy  A股-申万行业      1
2  sw_mrhl  A股-申万行业-美容护理     0     0     2  swhy  A股-申万行业      1
3    sw_hb    A股-申万行业-环保     0     0     2  swhy  A股-申万行业      1
4  sw_dlsb  A股-申万行业-电力设备     0     0     2  swhy  A股-申万行业      1

In [12]:
df[df['type1']=='3']

             code        name type1 type2 level  pcode pname isleaf
1223  bond.fundex    基金-封闭式基金     3    13     1  jijin    基金      1
1224      fundnet    基金-开放式基金     3    14     1  jijin    基金      1
1225    fundmoney    基金-货币型基金     3    15     1  jijin    基金      1
1226      fundnet  基金-ETF基金净值     3    16     1  jijin    基金      1
1227  bond.fundex  基金-ETF基金行情     3    17     1  jijin    基金      1
1228  bond.fundex  基金-LOF基金行情     3    18     1  jijin    基金      1
1229      fundnet    基金-科创板基金     3    21     1  jijin    基金      1
1230        jijin          基金     3  None     0                   0

In [13]:
df[df['type2']=='14']

         code      name type1 type2 level  pcode pname isleaf
1224  fundnet  基金-开放式基金     3    14     1  jijin    基金      1

In [14]:
df[df['pcode']=='sw2_hy']

           code           name type1 type2 level   pcode    pname isleaf
32   sw2_730200   A股-申万二级-通信设备     0     1     2  sw2_hy  A股-申万二级      1
33   sw2_730100   A股-申万二级-通信服务     0     1     2  sw2_hy  A股-申万二级      1
34   sw2_721000  A股-申万二级-电视广播Ⅱ     0     1     2  sw2_hy  A股-申万二级      1
35   sw2_720900     A股-申万二级-出版     0     1     2  sw2_hy  A股-申万二级      1
36   sw2_720700   A股-申万二级-数字媒体     0     1     2  sw2_hy  A股-申万二级      1
..          ...            ...   ...   ...   ...     ...      ...    ...
158  sw2_750300  A股-申万二级-炼化及贸易     0     1     2  sw2_hy  A股-申万二级      1
159  sw2_750200   A股-申万二级-油服工程     0     1     2  sw2_hy  A股-申万二级      1
160  sw2_750100  A股-申万二级-油气开采Ⅱ     0     1     2  sw2_hy  A股-申万二级      1
161  sw2_740200    A股-申万二级-焦炭Ⅱ     0     1     2  sw2_hy  A股-申万二级      1
162  sw2_740100   A股-申万二级-煤炭开采     0     1     2  sw2_hy  A股-申万二级      1

[131 rows x 8 columns]

#### 根据指数、行业、概念找相关股票
- API接口：`http://api.mairui.club/hszg/gg/指数、行业、概念代码/您的licence`
- 备用接口：`http://api1.mairui.club/hszg/gg/指数、行业、概念代码/您的licence`
- 接口说明：根据“指数、行业、概念树”接口得到的代码作为参数，得到相关的股票。
- 数据更新：每周六03:00更新
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |dm|string|代码（根据接口参数可能是A股股票代码，也可能是其他指数、行业、概念的股票代码）|
    |mc|string|名称（根据接口参数可能是A股股票代码，也可能是其他指数、行业、概念的股票名称）|
    |jys|string|交易所，sh表示上证，sz表示深证（如果返回的是A股的股票，那么有值，否则是null）|

In [15]:
ccode='sw2_480300'
url=f'http://api.mairui.club/hszg/gg/{ccode}/{licence}'
df=mydata_get(url)

In [16]:
df.head()

   code      dm    mc jys
0  None  601998  中信银行  sh
1  None  601916  浙商银行  sh
2  None  601818  光大银行  sh
3  None  601166  兴业银行  sh
4  None  600036  招商银行  sh

#### 根据股票找相关指数、行业、概念
- API接口：`http://api.mairui.club/hszg/zg/股票代码(如000001)/您的licence`
- 备用接口：`http://api1.mairui.club/hszg/zg/股票代码(如000001)/您的licence`
- 接口说明：根据《股票列表》得到的股票代码作为参数，得到相关的指数、行业、概念。
- 数据更新：每周六03:00更新
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |code|string|指数、行业、概念代码，如：sw2_650300|
    |name|string|指数、行业、概念名称，如：沪深股市-申万二级-国防军工-地面兵装|

In [17]:
ticker='000001'
url=f'http://api.mairui.club/hszg/zg/{ticker}/{licence}'
df=mydata_get(url)

In [18]:
df.head()

          code            name
0        sw_yx      A股-申万行业-银行
1   sw2_480300  A股-申万二级-股份制银行Ⅱ
2  chgn_700532  A股-热门概念-MSCI中国
3  chgn_700231     A股-热门概念-区块链
4  chgn_700095    A股-热门概念-融资融券

### 历史交易数据

#### 历史分时交易
- api接口：`http://api.mairui.club/hszbl/fsjy/股票代码(如000001)/分时级别/您的licence`
- 接口说明：根据《股票列表》得到的股票代码和分时级别获取历史交易数据，交易时间从远到近排序。目前 分时级别 支持5分钟、15分钟、30分钟、60分钟、日周月年级别（包括前后复权），对应的值分别是 5m（5分钟）、15m（15分钟）、30m（30分钟）、60m（60分钟）、dn(日线未复权)、dq（日线前复权）、dh（日线后复权）、wn(周线未复权)、wq（周线前复权）、wh（周线后复权）、mn(月线未复权)、mq（月线前复权）、mh（月线后复权）、yn(年线未复权)、yq（年线前复权）、yh（年线后复权） 。
- 数据更新：分钟级别数据盘中更新，分时越小越优先更新，如5分钟级别会每5分钟更新，15分钟级别会每15分钟更新，以此类推，日线及以上级别每天16:00更新。
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |d|string|交易时间，短分时级别格式为yyyy-MM-dd HH:mm:ss，日线级别为yyyy-MM-dd|
    |o|number|开盘价（元）|
    |h|number|最高价（元）|
    |l|number|最低价（元）|
    |c|number|收盘价（元）|
    |v|number|成交量（手）|
    |e|number|成交额（元）|
    |zf|number|振幅（%）|
    |hs|number|换手率（%）|
    |zd|number|涨跌幅（%）|
    |zde|number|涨跌额（元）|

In [48]:
fsjb='dq' # 分时级别
ticker='000001'
url=f'http://api.mairui.club/hszbl/fsjy/{ticker}/{fsjb}/{licence}'
df=mydata_get(url)

In [50]:
df.tail()

,d,o,h,l,c,v,e,zf,hs,zd,zde
7702,2023-07-05,11.36,11.40,11.30,11.34,423482,479726282.47,0.88,0.22,-0.53,-0.06
7703,2023-07-06,11.30,11.34,11.21,11.24,597096,672396816.40,1.15,0.31,-0.88,-0.10
7704,2023-07-07,11.20,11.27,11.18,11.20,484441,543212455.87,0.80,0.25,-0.36,-0.04
7705,2023-07-10,11.25,11.28,11.17,11.20,495882,556581581.65,0.98,0.26,0.00,0.00
7706,2023-07-11,11.22,11.26,11.19,11.21,570809,640131787.10,0.63,0.29,0.09,0.01

## [沪深指数数据](https://www.mairui.club/hszsdata.html)

### 指数列表

### 沪深主要指数列表接口
- API接口：`http://api.mairui.club/zs/all/您的licence`
- 备用接口：`http://api1.mairui.club/zs/all/您的licence`
- 接口说明：获取沪深两市主要的指数代码和名称，用于后续接口的参数传入。
- 数据更新：每天15:35点
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |dm|string|指数代码，如：sh000001（注意，股票代码可以不带“sh/sz”前缀，指数代码必须带）|
    |mc|string|股票名称，如：上证指数|
    |jys|string|交易所，sh表示上证，sz表示深证|

### 历史交易指标

#### 历史分时交易
- API接口：`http://api.mairui.club/zs/hfsjy/指数代码(如sh000001)/分时级别/您的licence`
- 备用接口：`http://api1.mairui.club/zs/hfsjy/指数代码(如sh000001)/分时级别/您的licence`
- 根据《指数列表》得到的指数代码（包含sh/sz前缀，如：sh000001）和分时级别获取历史交易数据，交易时间从远到近排序。目前 分时级别 支持5分钟、15分钟、30分钟、60分钟、日周月年级别，对应的值分别是 5m、15m、30m、60m、dn、wn、mn、yn 。
- 数据更新：分钟级别数据盘中更新，分时越小越优先更新，如5分钟级别会每5分钟更新，15分钟级别会每15分钟更新，以此类推，日线及以上级别每天15:35更新。
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |d|string|交易时间，短分时级别格式为yyyy-MM-dd HH:mm:ss，日线级别为yyyy-MM-dd|
    |o|number|开盘价（元）|
    |h|number|最高价（元）|
    |l|number|最低价（元）|
    |c|number|收盘价（元）|
    |v|number|成交量（手）|
    |e|number|成交额（元）|
    |zf|number|振幅（%）|
    |hs|number|换手率（%）|
    |zd|number|涨跌幅（%）|
    |zde|number|涨跌额（元）|

## [基金数据](https://www.mairui.club/jjdata.html)

### 基金列表

#### 所有基金列表
- API接口：`http://api.mairui.club/jj/all/您的licence`
- 备用接口：`http://api1.mairui.club/jj/all/您的licence`
- 接口说明：获取基金的代码和名称，用于其他接口的参数传入。
- 数据更新：每日16:00更新
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |dm|string|指数代码，如：sh000001（注意，股票代码可以不带“sh/sz”前缀，指数代码必须带）|
    |mc|string|股票名称，如：上证指数|
    |jys|string|交易所，sh表示上证，sz表示深证|

In [21]:
url=f'http://api.mairui.club/jj/all/{licence}'
df=mydata_get(url)

In [23]:
df[df['dm']=='510500']

          dm          mc tp
5391  510500  南方中证500ETF  1

### 估值及行情

#### ETF基金行情
- API接口：`http://api.mairui.club/jj/etfhq/ETF基金代码/您的licence`
- 备用接口：`http://api1.mairui.club/jj/etfhq/ETF基金代码/您的licence`
- 接口说明：根据《ETF基金列表》得到的基金代码作为参数获取基金的盘中行情。
- 数据更新：交易时间段每10分钟。
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |dm|string|基金代码|
    |mc|string|基金名称|
    |zxj|number|最新价|
    |zde|number|涨跌额|
    |zdf|number|涨跌幅（%）|
    |b|number|买入|
    |s|number|卖出|
    |zs|number|昨收|
    |jk|number|今开|
    |zg|number|最高|
    |zd|number|最低|
    |cjl|number|成交量（股）|
    |cje|number|成交额（元）|
    |t|number|时间 HH:mm:ss|

In [53]:
ticker='510500'
url=f'http://api.mairui.club/jj/etfhq/{ticker}/{licence}'
df=mydata_get(url)

ValueError: If using all scalar values, you must pass an index

### 技术指标

#### 最新K线
- API接口：`http://api.mairui.club/jj/zxkx/基金代码/分时级别/您的licence`
- 备用接口：`http://api1.mairui.club/jj/zxkx/基金代码/分时级别/您的licence`
- 接口说明：根据基金代码（《封闭式基金列表》、《ETF基金列表》、《LOF基金列表》接口获取的基金代码）获取最新K线数据。目前分时级别支持日、周、月级别，对应的参数分别是 dn、wn、mn
- 数据更新：每日16点更新。
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |d|string|交易时间，yyyy-MM-dd|
    |o|number|开盘价（元）|
    |h|number|最高价（元）|
    |l|number|最低价（元）|
    |c|number|收盘价（元）|
    |v|number|成交量（股）|
    |zde|number|涨跌额（元）|
    |zd|number|涨跌幅（%）|
    |zf|number|振幅（%）|

### 历史K线
- API接口：`http://api.mairui.club/jj/lskx/基金代码/分时级别/您的licence`
- 备用接口：`http://api1.mairui.club/jj/lskx/基金代码/分时级别/您的licence`
- 接口说明：根据基金代码（《封闭式基金列表》、《ETF基金列表》、《LOF基金列表》接口获取的基金代码）获取历史K线数据。目前分时级别支持日、周、月级别，对应的参数分别是 dn、wn、mn
- 数据更新：每日16点更新。
- 请求频率：1分钟20次
- 返回格式：标准Json格式 [{},...{}]
- 字段：
    |字段名称|数据类型|字段说明|
    |---|---|---|
    |d|string|交易时间，yyyy-MM-dd|
    |o|number|开盘价（元）|
    |h|number|最高价（元）|
    |l|number|最低价（元）|
    |c|number|收盘价（元）|
    |v|number|成交量（股）|
    |zde|number|涨跌额（元）|
    |zd|number|涨跌幅（%）|
    |zf|number|振幅（%）|

In [51]:
fsjb='dn'
ticker='510500'
url=f'http://api.mairui.club/jj/lskx/{ticker}/{fsjb}/{licence}'
df=mydata_get(url)

In [47]:
df.head()

Empty DataFrame
Columns: []
Index: []